---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-config
  namespace: default
data:
  Corefile: |
    .:53 {
        etcd {
            path /skydns
            endpoint http://etcd-home:2379
        }
        errors
        log . "{proto} {remote} is Request: {name} {type} {>id}"
        cache 30
        forward . 8.8.8.8 8.8.4.4
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns-home
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coredns-home
  template:
    metadata:
      labels:
        app: coredns-home
    spec:
      containers:
      - name: coredns
        image: coredns/coredns
        args: ["-conf", "/etc/coredns/Corefile"]
        ports:
        - containerPort: 53
          protocol: UDP
        - containerPort: 53
          protocol: TCP
        volumeMounts:
        - name: config-volume
          mountPath: /etc/coredns
      volumes:
      - name: config-volume
        configMap:
          name: coredns-config
---
apiVersion: v1
kind: Service
metadata:
  name: coredns-home
  namespace: default
spec:
  selector:
    app: coredns-home
  ports:
  - name: dns-udp
    protocol: UDP
    port: 53
    targetPort: 53
  - name: dns-tcp
    protocol: TCP
    port: 53
    targetPort: 53
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd-home
  namespace: default
spec:
  serviceName: "etcd-home"
  replicas: 1
  selector:
    matchLabels:
      app: etcd-home
  template:
    metadata:
      labels:
        app: etcd-home
    spec:
      containers:
      - name: etcd
        image: bitnami/etcd
        ports:
        - containerPort: 2379
        env:
        - name: ALLOW_NONE_AUTHENTICATION
          value: "yes"
        volumeMounts:
        - name: etcd-data
          mountPath: /bitnami/etcd
  volumeClaimTemplates:
  - metadata:
      name: etcd-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: etcd-home
  namespace: default
spec:
  selector:
    app: etcd-home
  ports:
  - port: 2379
    targetPort: 2379